# Generated by Django 3.0.2 on 2020-03-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chairman_Framework', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cognitive_domain',
            old_name='tags',
            new_name='verbs',
        ),
    ]
