# Generated by Django 3.0.2 on 2020-03-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chairman_Framework', '0002_auto_20200327_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affective_domain',
            old_name='tags',
            new_name='verbs',
        ),
        migrations.RenameField(
            model_name='psychomotor_domain',
            old_name='tags',
            new_name='verbs',
        ),
    ]
